config/routes.rb
Sproutify::Application.routes.draw do

  root :to => 'home#index'

  resources :users, :only => [:create] do
    resources :supplies, :only => [:index, :create, :destroy], module: "users"
    resources :demands, only: [:index], module: "users"
  end

  resources :supplies, :only => [:index, :create, :update, :destroy]
  resources :demands, only: [:create, :index, :destroy]


  resources :sessions, only: [:index, :create]

  delete '/sessions', to: 'sessions#destroy'

  get 'fetch', to: 'home#fetch'

  get 'search', to: 'search#search'

  get 'user_data', to: 'sessions#user_data'

  get 'inbox', to: 'users#inbox'

  get 'message', to: 'users#message'

  post 'connect', to: 'users#email_user'

  post 'respond', to: 'users#respond_to_user'
end

app/views/shared/_current_supply.html.haml
%h1 #{user.first_name}'s Current Supply

-@supplies.each do |supply|
	%li
		-crop = Crop.find(supply.crop_id).name
		-status = Status.find_by_id(supply.status_id)
		#{crop}'s current status is #{status ? status.name : 'empty'}
	%br

app/views/shared/_error.html.haml
.alert.alert-danger
  -if error_messages
    =error_messages.first

app/views/shared/_landing.html.haml
.container
  %h3 Find Gardeners near you
  =form_for :landing, html:{role: "form"} do |f|
    .form-group=f.text_field(:location, placeholder: "Street Address", class: "form-control", id:'address')
    .form-group=f.text_field(:location, placeholder: "Zip Code", class: "form-control", id:'zip')
    =f.submit "Submit", class: "btn btn-primary", id: "submit"

.signup-link
  =link_to "Signup!", '#', class: "btn btn-primary signup-link"
  
%input{type: "hidden", id: "hidden_lat"}
%input{type: "hidden", id: "hidden_lng"}

=render partial:"shared/signupmodal", locals: {user: @user}
=render partial:"shared/loginmodal", locals: {user: @user}

app/views/shared/_loginmodal.html.haml
.modal.fade#login-modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Sign in to Sproutify
      
      =form_for(user, as: :session, url: sessions_path, html:{role: "form"}) do |f|
        .modal-body
          .form-group=f.text_field :email, placeholder: "Email", class: "form-control"
          .form-group=f.password_field :password, placeholder: "Password", class: "form-control"
        .modal-footer
          =f.submit "Login", class: "btn btn-primary"

app/views/shared/_main.html.haml
%h1 What produce do you have available?

=form_tag supplies_path, method: 'post', remote: true, html:{role: "form"}, id: 'add-supplies-form' do
  .form-group=text_field :crop_name, nil, placeholder: "Crop name", class: "form-control"
  .form-group=text_field :status, nil, placeholder: "Status", class: "form-control"
  
  .form-group=select_tag :status, options_for_select(["Growing", "Harvesting", "Done"], "Growing")
  
  =submit_tag "Add Supply", class: "btn btn-primary"

.user-supplies

app/views/shared/_nav.html.haml
%nav.navbar{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
  / Collect the nav links, forms, and other content for toggling
  .collapse.navbar-collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav.navbar-right
      -if logged_in?
        =render "shared/nav_loggedin"
      -else
        =render "shared/nav_loggedout"

app/views/shared/_nav_loggedin.html.haml
%li
  =link_to "Logout", session_path(current_user), method: :delete, class: "logout-link"

app/views/shared/_nav_loggedout.html.haml
%li
  =link_to "Signup", '#', class: "signup-link"
%li
  =link_to "Login", '#', class: "login-link"

app/views/shared/_signupmodal.html.haml
.modal.fade#signup-modal{role: "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Become a gardener on Sproutify!

      =form_for user, html:{role: "form"} do |f|
        .modal-body
          .form-group=f.text_field :first_name, placeholder: "First Name", class: "form-control"
          .form-group=f.text_field :last_name, placeholder: "Last Name", class: "form-control"
          .form-group=f.text_field :email, placeholder: "Email", class: "form-control"
          .form-group=f.password_field :password, placeholder: "Password", class: "form-control"
          .form-group=f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control"
        .modal-footer
          =f.submit "Signup", class: "btn btn-primary"

app/views/shared/_static.html.haml
/ = render partial:"shared/nav"

/ #main-body
/   -if logged_in?
/     = render partial:"shared/main"
/   -else
/     = render partial:"shared/landing"

/   #test